# Generated by Django 2.0.4 on 2018-06-02 19:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atendimento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exame', models.FileField(upload_to='file_exames/%Y/%m/%d/')),
                ('data_entrega', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atendimento.Atendimento', verbose_name='Atendimento')),
            ],
        ),
    ]
