# Generated by Django 2.0.4 on 2018-06-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exame',
            name='tipo_exame',
            field=models.CharField(default=1, max_length=200, verbose_name='Nome do Exame'),
            preserve_default=False,
        ),
    ]
