# Generated by Django 2.0.4 on 2018-06-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exame', '0002_exame_tipo_exame'),
    ]

    operations = [
        migrations.AddField(
            model_name='exame',
            name='descricao',
            field=models.TextField(default=1, verbose_name='Descrição do Exame'),
            preserve_default=False,
        ),
    ]
