# Generated by Django 2.0.4 on 2018-05-16 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0002_auto_20180516_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkscriptshead',
            options={'verbose_name': 'Scripts do cabeçalho', 'verbose_name_plural': 'Scripts do cabeçalho'},
        ),
        migrations.AlterModelOptions(
            name='website',
            options={'verbose_name': 'Título do Website', 'verbose_name_plural': 'Títulos dos Websites'},
        ),
        migrations.AddField(
            model_name='website',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=True, to=settings.AUTH_USER_MODEL, verbose_name='User name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='linkscriptshead',
            name='href',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Caminho do Script'),
        ),
        migrations.AlterField(
            model_name='linkscriptshead',
            name='media',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Caminho do Script'),
        ),
        migrations.AlterField(
            model_name='linkscriptshead',
            name='rel',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Rel'),
        ),
        migrations.AlterField(
            model_name='linkscriptshead',
            name='type',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Tipo de script'),
        ),
    ]
