# Generated by Django 2.0.4 on 2018-05-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20180516_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='website',
            options={'verbose_name': 'Website', 'verbose_name_plural': 'Websites'},
        ),
        migrations.AddField(
            model_name='linkscriptshead',
            name='script_name',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Nome usado para identificar o script'),
        ),
    ]
