# Generated by Django 2.0.4 on 2018-05-16 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20180516_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='scripts',
            new_name='list_scripts',
        ),
    ]
