# Generated by Django 2.0.4 on 2018-06-02 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20180516_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkscriptshead',
            name='media',
        ),
    ]
