# Generated by Django 2.0.4 on 2018-06-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagem',
            field=models.FileField(default=1, upload_to='images/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
